### PR TITLE
Benbranch

### PR DESCRIPTION
**Pull request by BLbenjaminliu**
css changes. didn’t mess w/ other stuff (may have opened a few, but still not 100% on conflict resolution…)

### CODE REVIEW

**Comment by BLbenjaminliu** [comment]
just updated more css and stuff - shouldn't need to pull request again, right?

**Comment by joemelt101** [comment]
Yup that's right
- Jared Melton
  ________________________________

**Comment by BLbenjaminliu** [comment]
hm...there are def some problems (particularly login). i might save my differences locally and reclone =/
i know there are better ways, but this may be most straight forward for me now. should i go ahead and do this?

actually, would it be better to just pull in my actual changes (mostly css and other smaller things), reject other stuff where i might have messed w/ controller, and have a working premaster i could then reclone (like usual, lol)

**Comment by joemelt101** [comment]
Hey Ben, I don't think this is going to work... I think you haven't deleted and updated your repo with Homer's new premaster. Basically, delete your local repo (save the files that you actually changed). Re clone gamer-net into the same directory. git checkout premaster. git branch benCSS. Re copy the files that you actually changed over the existing ones or however you want to remake your changes. git push origin benCSS. Then do another pull request. I'm going to mark this one as closed. (Rejected)

**Pull request closed without merging**
