### PR TITLE
moved register and login functions that use the database to the model…

### PR DESCRIPTION
**Pull request by HomerGaidarski**
… where they belong

### CODE REVIEW

**Comment by HomerGaidarski** [comment]
Boooooooo the new checking system booooooooo

**Comment by joemelt101** [comment]
Muhahahaha
- Jared Melton
  ________________________________

**Comment by joemelt101** [comment]
#Approved :+1:

**Comment by joemelt101** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/joemelt101/gamer-net/pull-request/161/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=joemelt101/gamer-net)

**Pull request merged**
