### PR TITLE
Navbar / CSS fixed. 

### PR DESCRIPTION
**Pull request by amstl14**
#54

The background colors are applied through a css stylesheet called art.css, but to save time i just replaced everything inside of bootstrap.min.css

I check, and all the views are still working and look good. 

I'll rename and relink if needed.

### CODE REVIEW

**Comment by joemelt101** [comment]
What a champ!

**Comment by amstl14** [comment]
The search page doesn't have the CSS applied yet b/c I had conflicts when I tried to pull earlier, so I don't even have the view, but after you merge all changes I'll do a fresh clone tomorrow and finish.

**Comment by joemelt101** [comment]
Hey I added some issues to your name. Take a look at the ones you can tackle and let me know if you have questions.

**Comment by amstl14** [comment]
i closed it for a reason. keep it closed...

**Pull request closed without merging**
